// @generated by protoc-gen-es v2.8.0
// @generated from file base.proto (syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file base.proto.
 */
export const file_base = /*@__PURE__*/
  fileDesc("CgpiYXNlLnByb3RvIksKDkNvbW11bml0eUdyb3VwEgoKAmlkGAEgASgJEgwKBG5hbWUYAiABKAkSHwoLY29tbXVuaXRpZXMYAyADKAsyCi5Db21tdW5pdHkiJQoJQ29tbXVuaXR5EgoKAmlkGAEgASgJEgwKBG5hbWUYAiABKAlCM0IJQmFzZVByb3RvUAFaJGdpdGh1Yi5jb20vdmFyc28vcHJvdGNoYXQtc2VydmVyL2dlbmIGcHJvdG8z");

/**
 * Describes the message CommunityGroup.
 * Use `create(CommunityGroupSchema)` to create a new message.
 */
export const CommunityGroupSchema = /*@__PURE__*/
  messageDesc(file_base, 0);

/**
 * Describes the message Community.
 * Use `create(CommunitySchema)` to create a new message.
 */
export const CommunitySchema = /*@__PURE__*/
  messageDesc(file_base, 1);

