// @generated by protoc-gen-es v2.8.0
// @generated from file base.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file base.proto.
 */
export declare const file_base: GenFile;

/**
 * @generated from message CommunityGroup
 */
export declare type CommunityGroup = Message<"CommunityGroup"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: repeated Community communities = 3;
   */
  communities: Community[];
};

/**
 * Describes the message CommunityGroup.
 * Use `create(CommunityGroupSchema)` to create a new message.
 */
export declare const CommunityGroupSchema: GenMessage<CommunityGroup>;

/**
 * @generated from message Community
 */
export declare type Community = Message<"Community"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;
};

/**
 * Describes the message Community.
 * Use `create(CommunitySchema)` to create a new message.
 */
export declare const CommunitySchema: GenMessage<Community>;

