// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package communitydb

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Member struct {
	ID          uuid.UUID
	UserAddress string
	CreatedAt   pgtype.Timestamptz
}
