// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package communitydb

import (
	"context"

	"github.com/google/uuid"
)

const getMemberByUserAddress = `-- name: GetMemberByUserAddress :one
SELECT id, user_address, created_at FROM members WHERE user_address = $1
`

func (q *Queries) GetMemberByUserAddress(ctx context.Context, userAddress string) (Member, error) {
	row := q.db.QueryRow(ctx, getMemberByUserAddress, userAddress)
	var i Member
	err := row.Scan(&i.ID, &i.UserAddress, &i.CreatedAt)
	return i, err
}

const upsertMember = `-- name: UpsertMember :one
INSERT INTO members (id, user_address)
VALUES ($1, $2)
    ON CONFLICT (id, user_address) DO NOTHING
    RETURNING id, user_address, created_at
`

type UpsertMemberParams struct {
	ID          uuid.UUID
	UserAddress string
}

func (q *Queries) UpsertMember(ctx context.Context, arg UpsertMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, upsertMember, arg.ID, arg.UserAddress)
	var i Member
	err := row.Scan(&i.ID, &i.UserAddress, &i.CreatedAt)
	return i, err
}
