// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID           int64
	Username     string
	Email        pgtype.Text
	PasswordHash string
	CreateTime   pgtype.Timestamptz
}
