// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID           uuid.UUID
	Username     string
	Email        pgtype.Text
	PasswordHash pgtype.Text
	CreatedAt    pgtype.Timestamptz
}
