// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package postgres

import (
	"context"
)

const createAnonymousUser = `-- name: CreateAnonymousUser :one
INSERT INTO users (id, username) 
VALUES ($1, $2) 
RETURNING id, username, email, password_hash, create_time
`

type CreateAnonymousUserParams struct {
	ID       int64
	Username string
}

func (q *Queries) CreateAnonymousUser(ctx context.Context, arg CreateAnonymousUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createAnonymousUser, arg.ID, arg.Username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreateTime,
	)
	return i, err
}
