// @generated by protoc-gen-es v2.8.0
// @generated from file homeserver/v1/homeserver.proto (package homeserver.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message as Message$1 } from "@bufbuild/protobuf";

/**
 * Describes the file homeserver/v1/homeserver.proto.
 */
export declare const file_homeserver_v1_homeserver: GenFile;

/**
 * @generated from message homeserver.v1.Message
 */
export declare type Message = Message$1<"homeserver.v1.Message"> & {
  /**
   * @generated from field: homeserver.v1.Message.Type type = 1;
   */
  type: Message_Type;

  /**
   * @generated from field: bytes payload = 2;
   */
  payload: Uint8Array;

  /**
   * @generated from field: homeserver.v1.Message.Error error = 3;
   */
  error?: Message_Error;
};

/**
 * Describes the message homeserver.v1.Message.
 * Use `create(MessageSchema)` to create a new message.
 */
export declare const MessageSchema: GenMessage<Message>;

/**
 * @generated from message homeserver.v1.Message.Error
 */
export declare type Message_Error = Message$1<"homeserver.v1.Message.Error"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;
};

/**
 * Describes the message homeserver.v1.Message.Error.
 * Use `create(Message_ErrorSchema)` to create a new message.
 */
export declare const Message_ErrorSchema: GenMessage<Message_Error>;

/**
 * @generated from enum homeserver.v1.Message.Type
 */
export enum Message_Type {
  /**
   * @generated from enum value: TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: TYPE_ADD_USER_SERVER = 1;
   */
  ADD_USER_SERVER = 1,

  /**
   * @generated from enum value: TYPE_GET_USER_SERVERS = 2;
   */
  GET_USER_SERVERS = 2,
}

/**
 * Describes the enum homeserver.v1.Message.Type.
 */
export declare const Message_TypeSchema: GenEnum<Message_Type>;

/**
 * @generated from message homeserver.v1.AddUserServerRequest
 */
export declare type AddUserServerRequest = Message$1<"homeserver.v1.AddUserServerRequest"> & {
  /**
   * @generated from field: string host = 1;
   */
  host: string;
};

/**
 * Describes the message homeserver.v1.AddUserServerRequest.
 * Use `create(AddUserServerRequestSchema)` to create a new message.
 */
export declare const AddUserServerRequestSchema: GenMessage<AddUserServerRequest>;

/**
 * @generated from message homeserver.v1.AddUserServerResponse
 */
export declare type AddUserServerResponse = Message$1<"homeserver.v1.AddUserServerResponse"> & {
};

/**
 * Describes the message homeserver.v1.AddUserServerResponse.
 * Use `create(AddUserServerResponseSchema)` to create a new message.
 */
export declare const AddUserServerResponseSchema: GenMessage<AddUserServerResponse>;

/**
 * @generated from message homeserver.v1.GetUserServersRequest
 */
export declare type GetUserServersRequest = Message$1<"homeserver.v1.GetUserServersRequest"> & {
};

/**
 * Describes the message homeserver.v1.GetUserServersRequest.
 * Use `create(GetUserServersRequestSchema)` to create a new message.
 */
export declare const GetUserServersRequestSchema: GenMessage<GetUserServersRequest>;

/**
 * @generated from message homeserver.v1.GetUserServersResponse
 */
export declare type GetUserServersResponse = Message$1<"homeserver.v1.GetUserServersResponse"> & {
  /**
   * @generated from field: repeated homeserver.v1.GetUserServersResponse.Server servers = 1;
   */
  servers: GetUserServersResponse_Server[];
};

/**
 * Describes the message homeserver.v1.GetUserServersResponse.
 * Use `create(GetUserServersResponseSchema)` to create a new message.
 */
export declare const GetUserServersResponseSchema: GenMessage<GetUserServersResponse>;

/**
 * @generated from message homeserver.v1.GetUserServersResponse.Server
 */
export declare type GetUserServersResponse_Server = Message$1<"homeserver.v1.GetUserServersResponse.Server"> & {
  /**
   * @generated from field: string host = 1;
   */
  host: string;
};

/**
 * Describes the message homeserver.v1.GetUserServersResponse.Server.
 * Use `create(GetUserServersResponse_ServerSchema)` to create a new message.
 */
export declare const GetUserServersResponse_ServerSchema: GenMessage<GetUserServersResponse_Server>;

