// @generated by protoc-gen-es v2.8.0
// @generated from file homeserver/v1/homeserver.proto (package homeserver.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message as Message$1 } from "@bufbuild/protobuf";

/**
 * Describes the file homeserver/v1/homeserver.proto.
 */
export declare const file_homeserver_v1_homeserver: GenFile;

/**
 * @generated from message homeserver.v1.Message
 */
export declare type Message = Message$1<"homeserver.v1.Message"> & {
  /**
   * @generated from field: homeserver.v1.Message.Type type = 1;
   */
  type: Message_Type;

  /**
   * @generated from field: bytes payload = 2;
   */
  payload: Uint8Array;

  /**
   * @generated from field: homeserver.v1.Message.Error error = 3;
   */
  error?: Message_Error;
};

/**
 * Describes the message homeserver.v1.Message.
 * Use `create(MessageSchema)` to create a new message.
 */
export declare const MessageSchema: GenMessage<Message>;

/**
 * @generated from message homeserver.v1.Message.Error
 */
export declare type Message_Error = Message$1<"homeserver.v1.Message.Error"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;
};

/**
 * Describes the message homeserver.v1.Message.Error.
 * Use `create(Message_ErrorSchema)` to create a new message.
 */
export declare const Message_ErrorSchema: GenMessage<Message_Error>;

/**
 * @generated from enum homeserver.v1.Message.Type
 */
export enum Message_Type {
  /**
   * @generated from enum value: TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: TYPE_ADD_USER_SERVER = 1;
   */
  ADD_USER_SERVER = 1,

  /**
   * @generated from enum value: TYPE_GET_USER_COMMUNITIES = 2;
   */
  GET_USER_COMMUNITIES = 2,

  /**
   * @generated from enum value: TYPE_GET_IDENTITY_TOKEN = 3;
   */
  GET_IDENTITY_TOKEN = 3,

  /**
   * @generated from enum value: TYPE_JOIN_COMMUNITY_SERVER = 4;
   */
  JOIN_COMMUNITY_SERVER = 4,
}

/**
 * Describes the enum homeserver.v1.Message.Type.
 */
export declare const Message_TypeSchema: GenEnum<Message_Type>;

/**
 * @generated from message homeserver.v1.AddUserServerRequest
 */
export declare type AddUserServerRequest = Message$1<"homeserver.v1.AddUserServerRequest"> & {
  /**
   * @generated from field: string host = 1;
   */
  host: string;
};

/**
 * Describes the message homeserver.v1.AddUserServerRequest.
 * Use `create(AddUserServerRequestSchema)` to create a new message.
 */
export declare const AddUserServerRequestSchema: GenMessage<AddUserServerRequest>;

/**
 * @generated from message homeserver.v1.AddUserServerResponse
 */
export declare type AddUserServerResponse = Message$1<"homeserver.v1.AddUserServerResponse"> & {
};

/**
 * Describes the message homeserver.v1.AddUserServerResponse.
 * Use `create(AddUserServerResponseSchema)` to create a new message.
 */
export declare const AddUserServerResponseSchema: GenMessage<AddUserServerResponse>;

/**
 * @generated from message homeserver.v1.GetUserCommunitiesRequest
 */
export declare type GetUserCommunitiesRequest = Message$1<"homeserver.v1.GetUserCommunitiesRequest"> & {
};

/**
 * Describes the message homeserver.v1.GetUserCommunitiesRequest.
 * Use `create(GetUserCommunitiesRequestSchema)` to create a new message.
 */
export declare const GetUserCommunitiesRequestSchema: GenMessage<GetUserCommunitiesRequest>;

/**
 * @generated from message homeserver.v1.GetUserCommunitiesResponse
 */
export declare type GetUserCommunitiesResponse = Message$1<"homeserver.v1.GetUserCommunitiesResponse"> & {
  /**
   * @generated from field: repeated homeserver.v1.GetUserCommunitiesResponse.Community communities = 1;
   */
  communities: GetUserCommunitiesResponse_Community[];
};

/**
 * Describes the message homeserver.v1.GetUserCommunitiesResponse.
 * Use `create(GetUserCommunitiesResponseSchema)` to create a new message.
 */
export declare const GetUserCommunitiesResponseSchema: GenMessage<GetUserCommunitiesResponse>;

/**
 * @generated from message homeserver.v1.GetUserCommunitiesResponse.Community
 */
export declare type GetUserCommunitiesResponse_Community = Message$1<"homeserver.v1.GetUserCommunitiesResponse.Community"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;
};

/**
 * Describes the message homeserver.v1.GetUserCommunitiesResponse.Community.
 * Use `create(GetUserCommunitiesResponse_CommunitySchema)` to create a new message.
 */
export declare const GetUserCommunitiesResponse_CommunitySchema: GenMessage<GetUserCommunitiesResponse_Community>;

/**
 * @generated from message homeserver.v1.WellKnown
 */
export declare type WellKnown = Message$1<"homeserver.v1.WellKnown"> & {
  /**
   * @generated from field: string public_key = 1;
   */
  publicKey: string;
};

/**
 * Describes the message homeserver.v1.WellKnown.
 * Use `create(WellKnownSchema)` to create a new message.
 */
export declare const WellKnownSchema: GenMessage<WellKnown>;

/**
 * @generated from message homeserver.v1.GetIdentityTokenRequest
 */
export declare type GetIdentityTokenRequest = Message$1<"homeserver.v1.GetIdentityTokenRequest"> & {
};

/**
 * Describes the message homeserver.v1.GetIdentityTokenRequest.
 * Use `create(GetIdentityTokenRequestSchema)` to create a new message.
 */
export declare const GetIdentityTokenRequestSchema: GenMessage<GetIdentityTokenRequest>;

/**
 * @generated from message homeserver.v1.GetIdentityTokenResponse
 */
export declare type GetIdentityTokenResponse = Message$1<"homeserver.v1.GetIdentityTokenResponse"> & {
  /**
   * @generated from field: string token = 1;
   */
  token: string;
};

/**
 * Describes the message homeserver.v1.GetIdentityTokenResponse.
 * Use `create(GetIdentityTokenResponseSchema)` to create a new message.
 */
export declare const GetIdentityTokenResponseSchema: GenMessage<GetIdentityTokenResponse>;

/**
 * @generated from message homeserver.v1.JoinCommunityServerRequest
 */
export declare type JoinCommunityServerRequest = Message$1<"homeserver.v1.JoinCommunityServerRequest"> & {
  /**
   * @generated from field: string host = 1;
   */
  host: string;
};

/**
 * Describes the message homeserver.v1.JoinCommunityServerRequest.
 * Use `create(JoinCommunityServerRequestSchema)` to create a new message.
 */
export declare const JoinCommunityServerRequestSchema: GenMessage<JoinCommunityServerRequest>;

/**
 * @generated from message homeserver.v1.JoinCommunityServerResponse
 */
export declare type JoinCommunityServerResponse = Message$1<"homeserver.v1.JoinCommunityServerResponse"> & {
};

/**
 * Describes the message homeserver.v1.JoinCommunityServerResponse.
 * Use `create(JoinCommunityServerResponseSchema)` to create a new message.
 */
export declare const JoinCommunityServerResponseSchema: GenMessage<JoinCommunityServerResponse>;

