// @generated by protoc-gen-es v2.8.0
// @generated from file homeserver/v1/homeserver.proto (package homeserver.v1, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file homeserver/v1/homeserver.proto.
 */
export const file_homeserver_v1_homeserver = /*@__PURE__*/
  fileDesc("Ch5ob21lc2VydmVyL3YxL2hvbWVzZXJ2ZXIucHJvdG8SDWhvbWVzZXJ2ZXIudjEi3wEKB01lc3NhZ2USKQoEdHlwZRgBIAEoDjIbLmhvbWVzZXJ2ZXIudjEuTWVzc2FnZS5UeXBlEg8KB3BheWxvYWQYAiABKAwSKwoFZXJyb3IYAyABKAsyHC5ob21lc2VydmVyLnYxLk1lc3NhZ2UuRXJyb3IaGAoFRXJyb3ISDwoHbWVzc2FnZRgBIAEoCSJRCgRUeXBlEhQKEFRZUEVfVU5TUEVDSUZJRUQQABIYChRUWVBFX0FERF9VU0VSX1NFUlZFUhABEhkKFVRZUEVfR0VUX1VTRVJfU0VSVkVSUxACIiQKFEFkZFVzZXJTZXJ2ZXJSZXF1ZXN0EgwKBGhvc3QYASABKAkiFwoVQWRkVXNlclNlcnZlclJlc3BvbnNlIhcKFUdldFVzZXJTZXJ2ZXJzUmVxdWVzdCJvChZHZXRVc2VyU2VydmVyc1Jlc3BvbnNlEj0KB3NlcnZlcnMYASADKAsyLC5ob21lc2VydmVyLnYxLkdldFVzZXJTZXJ2ZXJzUmVzcG9uc2UuU2VydmVyGhYKBlNlcnZlchIMCgRob3N0GAEgASgJQsoBChFjb20uaG9tZXNlcnZlci52MUIPSG9tZXNlcnZlclByb3RvUAFaT2dpdGh1Yi5jb20vdmFyc28vcHJvdGNoYXQtc2VydmVyL2ludGVybmFsL21vZGVscy9nZW4vaG9tZXNlcnZlci92MTtob21lc2VydmVydjGiAgNIWFiqAg1Ib21lc2VydmVyLlYxygINSG9tZXNlcnZlclxWMeICGUhvbWVzZXJ2ZXJcVjFcR1BCTWV0YWRhdGHqAg5Ib21lc2VydmVyOjpWMWIGcHJvdG8z");

/**
 * Describes the message homeserver.v1.Message.
 * Use `create(MessageSchema)` to create a new message.
 */
export const MessageSchema = /*@__PURE__*/
  messageDesc(file_homeserver_v1_homeserver, 0);

/**
 * Describes the message homeserver.v1.Message.Error.
 * Use `create(Message_ErrorSchema)` to create a new message.
 */
export const Message_ErrorSchema = /*@__PURE__*/
  messageDesc(file_homeserver_v1_homeserver, 0, 0);

/**
 * Describes the enum homeserver.v1.Message.Type.
 */
export const Message_TypeSchema = /*@__PURE__*/
  enumDesc(file_homeserver_v1_homeserver, 0, 0);

/**
 * @generated from enum homeserver.v1.Message.Type
 */
export const Message_Type = /*@__PURE__*/
  tsEnum(Message_TypeSchema);

/**
 * Describes the message homeserver.v1.AddUserServerRequest.
 * Use `create(AddUserServerRequestSchema)` to create a new message.
 */
export const AddUserServerRequestSchema = /*@__PURE__*/
  messageDesc(file_homeserver_v1_homeserver, 1);

/**
 * Describes the message homeserver.v1.AddUserServerResponse.
 * Use `create(AddUserServerResponseSchema)` to create a new message.
 */
export const AddUserServerResponseSchema = /*@__PURE__*/
  messageDesc(file_homeserver_v1_homeserver, 2);

/**
 * Describes the message homeserver.v1.GetUserServersRequest.
 * Use `create(GetUserServersRequestSchema)` to create a new message.
 */
export const GetUserServersRequestSchema = /*@__PURE__*/
  messageDesc(file_homeserver_v1_homeserver, 3);

/**
 * Describes the message homeserver.v1.GetUserServersResponse.
 * Use `create(GetUserServersResponseSchema)` to create a new message.
 */
export const GetUserServersResponseSchema = /*@__PURE__*/
  messageDesc(file_homeserver_v1_homeserver, 4);

/**
 * Describes the message homeserver.v1.GetUserServersResponse.Server.
 * Use `create(GetUserServersResponse_ServerSchema)` to create a new message.
 */
export const GetUserServersResponse_ServerSchema = /*@__PURE__*/
  messageDesc(file_homeserver_v1_homeserver, 4, 0);

