// @generated by protoc-gen-es v2.8.0
// @generated from file communityserver/v1/communityserver.proto (package communityserver.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file communityserver/v1/communityserver.proto.
 */
export const file_communityserver_v1_communityserver = /*@__PURE__*/
  fileDesc("Cihjb21tdW5pdHlzZXJ2ZXIvdjEvY29tbXVuaXR5c2VydmVyLnByb3RvEhJjb21tdW5pdHlzZXJ2ZXIudjEiGwoZR2V0VXNlckNvbW11bml0aWVzUmVxdWVzdCKSAQoaR2V0VXNlckNvbW11bml0aWVzUmVzcG9uc2USTQoLY29tbXVuaXRpZXMYASADKAsyOC5jb21tdW5pdHlzZXJ2ZXIudjEuR2V0VXNlckNvbW11bml0aWVzUmVzcG9uc2UuQ29tbXVuaXR5GiUKCUNvbW11bml0eRIKCgJpZBgBIAEoCRIMCgRuYW1lGAIgASgJIjMKEUpvaW5TZXJ2ZXJSZXF1ZXN0Eh4KFmpvaW5fZGVmYXVsdF9jb21tdW5pdHkYASABKAgiFAoSSm9pblNlcnZlclJlc3BvbnNlQvIBChZjb20uY29tbXVuaXR5c2VydmVyLnYxQhRDb21tdW5pdHlzZXJ2ZXJQcm90b1ABWllnaXRodWIuY29tL3ZhcnNvL3Byb3RjaGF0LXNlcnZlci9pbnRlcm5hbC9tb2RlbHMvZ2VuL2NvbW11bml0eXNlcnZlci92MTtjb21tdW5pdHlzZXJ2ZXJ2MaICA0NYWKoCEkNvbW11bml0eXNlcnZlci5WMcoCEkNvbW11bml0eXNlcnZlclxWMeICHkNvbW11bml0eXNlcnZlclxWMVxHUEJNZXRhZGF0YeoCE0NvbW11bml0eXNlcnZlcjo6VjFiBnByb3RvMw");

/**
 * Describes the message communityserver.v1.GetUserCommunitiesRequest.
 * Use `create(GetUserCommunitiesRequestSchema)` to create a new message.
 */
export const GetUserCommunitiesRequestSchema = /*@__PURE__*/
  messageDesc(file_communityserver_v1_communityserver, 0);

/**
 * Describes the message communityserver.v1.GetUserCommunitiesResponse.
 * Use `create(GetUserCommunitiesResponseSchema)` to create a new message.
 */
export const GetUserCommunitiesResponseSchema = /*@__PURE__*/
  messageDesc(file_communityserver_v1_communityserver, 1);

/**
 * Describes the message communityserver.v1.GetUserCommunitiesResponse.Community.
 * Use `create(GetUserCommunitiesResponse_CommunitySchema)` to create a new message.
 */
export const GetUserCommunitiesResponse_CommunitySchema = /*@__PURE__*/
  messageDesc(file_communityserver_v1_communityserver, 1, 0);

/**
 * Describes the message communityserver.v1.JoinServerRequest.
 * Use `create(JoinServerRequestSchema)` to create a new message.
 */
export const JoinServerRequestSchema = /*@__PURE__*/
  messageDesc(file_communityserver_v1_communityserver, 2);

/**
 * Describes the message communityserver.v1.JoinServerResponse.
 * Use `create(JoinServerResponseSchema)` to create a new message.
 */
export const JoinServerResponseSchema = /*@__PURE__*/
  messageDesc(file_communityserver_v1_communityserver, 3);

