// @generated by protoc-gen-es v2.8.0
// @generated from file communityserver/v1/communityserver.proto (package communityserver.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file communityserver/v1/communityserver.proto.
 */
export declare const file_communityserver_v1_communityserver: GenFile;

/**
 * @generated from message communityserver.v1.GetUserCommunitiesRequest
 */
export declare type GetUserCommunitiesRequest = Message<"communityserver.v1.GetUserCommunitiesRequest"> & {
};

/**
 * Describes the message communityserver.v1.GetUserCommunitiesRequest.
 * Use `create(GetUserCommunitiesRequestSchema)` to create a new message.
 */
export declare const GetUserCommunitiesRequestSchema: GenMessage<GetUserCommunitiesRequest>;

/**
 * @generated from message communityserver.v1.GetUserCommunitiesResponse
 */
export declare type GetUserCommunitiesResponse = Message<"communityserver.v1.GetUserCommunitiesResponse"> & {
  /**
   * @generated from field: repeated communityserver.v1.GetUserCommunitiesResponse.Community communities = 1;
   */
  communities: GetUserCommunitiesResponse_Community[];
};

/**
 * Describes the message communityserver.v1.GetUserCommunitiesResponse.
 * Use `create(GetUserCommunitiesResponseSchema)` to create a new message.
 */
export declare const GetUserCommunitiesResponseSchema: GenMessage<GetUserCommunitiesResponse>;

/**
 * @generated from message communityserver.v1.GetUserCommunitiesResponse.Community
 */
export declare type GetUserCommunitiesResponse_Community = Message<"communityserver.v1.GetUserCommunitiesResponse.Community"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;
};

/**
 * Describes the message communityserver.v1.GetUserCommunitiesResponse.Community.
 * Use `create(GetUserCommunitiesResponse_CommunitySchema)` to create a new message.
 */
export declare const GetUserCommunitiesResponse_CommunitySchema: GenMessage<GetUserCommunitiesResponse_Community>;

/**
 * @generated from message communityserver.v1.JoinServerRequest
 */
export declare type JoinServerRequest = Message<"communityserver.v1.JoinServerRequest"> & {
};

/**
 * Describes the message communityserver.v1.JoinServerRequest.
 * Use `create(JoinServerRequestSchema)` to create a new message.
 */
export declare const JoinServerRequestSchema: GenMessage<JoinServerRequest>;

/**
 * @generated from message communityserver.v1.JoinServerResponse
 */
export declare type JoinServerResponse = Message<"communityserver.v1.JoinServerResponse"> & {
};

/**
 * Describes the message communityserver.v1.JoinServerResponse.
 * Use `create(JoinServerResponseSchema)` to create a new message.
 */
export declare const JoinServerResponseSchema: GenMessage<JoinServerResponse>;

