// @generated by protoc-gen-es v2.8.0
// @generated from file communityserver/v1/communityserver.proto (package communityserver.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file communityserver/v1/communityserver.proto.
 */
export const file_communityserver_v1_communityserver = /*@__PURE__*/
  fileDesc("Cihjb21tdW5pdHlzZXJ2ZXIvdjEvY29tbXVuaXR5c2VydmVyLnByb3RvEhJjb21tdW5pdHlzZXJ2ZXIudjEiGwoZR2V0VXNlckNvbW11bml0aWVzUmVxdWVzdCKSAQoaR2V0VXNlckNvbW11bml0aWVzUmVzcG9uc2USTQoLY29tbXVuaXRpZXMYASADKAsyOC5jb21tdW5pdHlzZXJ2ZXIudjEuR2V0VXNlckNvbW11bml0aWVzUmVzcG9uc2UuQ29tbXVuaXR5GiUKCUNvbW11bml0eRIKCgJpZBgBIAEoCRIMCgRuYW1lGAIgASgJIhMKEUpvaW5TZXJ2ZXJSZXF1ZXN0IhQKEkpvaW5TZXJ2ZXJSZXNwb25zZULyAQoWY29tLmNvbW11bml0eXNlcnZlci52MUIUQ29tbXVuaXR5c2VydmVyUHJvdG9QAVpZZ2l0aHViLmNvbS92YXJzby9wcm90Y2hhdC1zZXJ2ZXIvaW50ZXJuYWwvbW9kZWxzL2dlbi9jb21tdW5pdHlzZXJ2ZXIvdjE7Y29tbXVuaXR5c2VydmVydjGiAgNDWFiqAhJDb21tdW5pdHlzZXJ2ZXIuVjHKAhJDb21tdW5pdHlzZXJ2ZXJcVjHiAh5Db21tdW5pdHlzZXJ2ZXJcVjFcR1BCTWV0YWRhdGHqAhNDb21tdW5pdHlzZXJ2ZXI6OlYxYgZwcm90bzM");

/**
 * Describes the message communityserver.v1.GetUserCommunitiesRequest.
 * Use `create(GetUserCommunitiesRequestSchema)` to create a new message.
 */
export const GetUserCommunitiesRequestSchema = /*@__PURE__*/
  messageDesc(file_communityserver_v1_communityserver, 0);

/**
 * Describes the message communityserver.v1.GetUserCommunitiesResponse.
 * Use `create(GetUserCommunitiesResponseSchema)` to create a new message.
 */
export const GetUserCommunitiesResponseSchema = /*@__PURE__*/
  messageDesc(file_communityserver_v1_communityserver, 1);

/**
 * Describes the message communityserver.v1.GetUserCommunitiesResponse.Community.
 * Use `create(GetUserCommunitiesResponse_CommunitySchema)` to create a new message.
 */
export const GetUserCommunitiesResponse_CommunitySchema = /*@__PURE__*/
  messageDesc(file_communityserver_v1_communityserver, 1, 0);

/**
 * Describes the message communityserver.v1.JoinServerRequest.
 * Use `create(JoinServerRequestSchema)` to create a new message.
 */
export const JoinServerRequestSchema = /*@__PURE__*/
  messageDesc(file_communityserver_v1_communityserver, 2);

/**
 * Describes the message communityserver.v1.JoinServerResponse.
 * Use `create(JoinServerResponseSchema)` to create a new message.
 */
export const JoinServerResponseSchema = /*@__PURE__*/
  messageDesc(file_communityserver_v1_communityserver, 3);

