// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package homeserverdb

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID           uuid.UUID
	Username     string
	DisplayName  pgtype.Text
	Email        pgtype.Text
	PasswordHash pgtype.Text
	CreatedAt    pgtype.Timestamptz
}

type UserServer struct {
	ID        int64
	UserID    uuid.UUID
	Host      string
	CreatedAt pgtype.Timestamptz
}
