// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package homeserverdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAnonymousUser = `-- name: CreateAnonymousUser :one
INSERT INTO users (id, username, display_name)
VALUES ($1, $2, $3)
    RETURNING id, username, display_name, email, password_hash, created_at
`

type CreateAnonymousUserParams struct {
	ID          uuid.UUID
	Username    string
	DisplayName pgtype.Text
}

func (q *Queries) CreateAnonymousUser(ctx context.Context, arg CreateAnonymousUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createAnonymousUser, arg.ID, arg.Username, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, username, display_name, email, password_hash)
VALUES ($1, $2, $3, $4, $5)
    RETURNING id, username, display_name, email, password_hash, created_at
`

type CreateUserParams struct {
	ID           uuid.UUID
	Username     string
	DisplayName  pgtype.Text
	Email        pgtype.Text
	PasswordHash pgtype.Text
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.DisplayName,
		arg.Email,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, username, display_name, email FROM users WHERE id = $1
`

type GetUserByIdRow struct {
	ID          uuid.UUID
	Username    string
	DisplayName pgtype.Text
	Email       pgtype.Text
}

func (q *Queries) GetUserById(ctx context.Context, id uuid.UUID) (GetUserByIdRow, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i GetUserByIdRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
	)
	return i, err
}

const getUserByLogin = `-- name: GetUserByLogin :one
SELECT id, username, display_name, email, password_hash, created_at FROM users WHERE username = $1 OR email = $1
`

func (q *Queries) GetUserByLogin(ctx context.Context, login string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByLogin, login)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserServers = `-- name: GetUserServers :many
SELECT host FROM user_servers WHERE user_id = $1
`

func (q *Queries) GetUserServers(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserServers, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var host string
		if err := rows.Scan(&host); err != nil {
			return nil, err
		}
		items = append(items, host)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUserServer = `-- name: UpsertUserServer :one
INSERT INTO user_servers (user_id, host)
VALUES ($1, $2)
    ON CONFLICT (user_id, host) DO NOTHING
    RETURNING id, user_id, host, created_at
`

type UpsertUserServerParams struct {
	UserID uuid.UUID
	Host   string
}

func (q *Queries) UpsertUserServer(ctx context.Context, arg UpsertUserServerParams) (UserServer, error) {
	row := q.db.QueryRow(ctx, upsertUserServer, arg.UserID, arg.Host)
	var i UserServer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Host,
		&i.CreatedAt,
	)
	return i, err
}
