// @generated by protoc-gen-es v2.8.0
// @generated from file prochat/v1/auth.proto (package prochat.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file prochat/v1/auth.proto.
 */
export const file_prochat_v1_auth = /*@__PURE__*/
  fileDesc("ChVwcm9jaGF0L3YxL2F1dGgucHJvdG8SCnByb2NoYXQudjEiRAoPUmVnaXN0ZXJSZXF1ZXN0EhAKCHVzZXJuYW1lGAEgASgJEg0KBWVtYWlsGAIgASgJEhAKCHBhc3N3b3JkGAMgASgJQp8BCg5jb20ucHJvY2hhdC52MUIJQXV0aFByb3RvUAFaOWdpdGh1Yi5jb20vdmFyc28vcHJvdGNoYXQtc2VydmVyL2dlbi9wcm9jaGF0L3YxO3Byb2NoYXR2MaICA1BYWKoCClByb2NoYXQuVjHKAgpQcm9jaGF0XFYx4gIWUHJvY2hhdFxWMVxHUEJNZXRhZGF0YeoCC1Byb2NoYXQ6OlYxYgZwcm90bzM");

/**
 * Describes the message prochat.v1.RegisterRequest.
 * Use `create(RegisterRequestSchema)` to create a new message.
 */
export const RegisterRequestSchema = /*@__PURE__*/
  messageDesc(file_prochat_v1_auth, 0);

