// @generated by protoc-gen-es v2.8.0
// @generated from file prochat/v1/auth.proto (package prochat.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file prochat/v1/auth.proto.
 */
export declare const file_prochat_v1_auth: GenFile;

/**
 * @generated from message prochat.v1.RegisterRequest
 */
export declare type RegisterRequest = Message<"prochat.v1.RegisterRequest"> & {
  /**
   * @generated from field: string user = 1;
   */
  user: string;

  /**
   * @generated from field: string email = 2;
   */
  email: string;

  /**
   * @generated from field: string password = 3;
   */
  password: string;

  /**
   * @generated from field: string fingerprint = 4;
   */
  fingerprint: string;
};

/**
 * Describes the message prochat.v1.RegisterRequest.
 * Use `create(RegisterRequestSchema)` to create a new message.
 */
export declare const RegisterRequestSchema: GenMessage<RegisterRequest>;

