// @generated by protoc-gen-es v2.8.0
// @generated from file prochat/v1/auth.proto (package prochat.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file prochat/v1/auth.proto.
 */
export const file_prochat_v1_auth = /*@__PURE__*/
  fileDesc("ChVwcm9jaGF0L3YxL2F1dGgucHJvdG8SCnByb2NoYXQudjEiVQoPUmVnaXN0ZXJSZXF1ZXN0EgwKBHVzZXIYASABKAkSDQoFZW1haWwYAiABKAkSEAoIcGFzc3dvcmQYAyABKAkSEwoLZmluZ2VycHJpbnQYBCABKAlCnwEKDmNvbS5wcm9jaGF0LnYxQglBdXRoUHJvdG9QAVo5Z2l0aHViLmNvbS92YXJzby9wcm90Y2hhdC1zZXJ2ZXIvZ2VuL3Byb2NoYXQvdjE7cHJvY2hhdHYxogIDUFhYqgIKUHJvY2hhdC5WMcoCClByb2NoYXRcVjHiAhZQcm9jaGF0XFYxXEdQQk1ldGFkYXRh6gILUHJvY2hhdDo6VjFiBnByb3RvMw");

/**
 * Describes the message prochat.v1.RegisterRequest.
 * Use `create(RegisterRequestSchema)` to create a new message.
 */
export const RegisterRequestSchema = /*@__PURE__*/
  messageDesc(file_prochat_v1_auth, 0);

