// @generated by protoc-gen-es v2.8.0
// @generated from file prochat/v1/base.proto (package prochat.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file prochat/v1/base.proto.
 */
export declare const file_prochat_v1_base: GenFile;

/**
 * @generated from message prochat.v1.CommunityGroup
 */
export declare type CommunityGroup = Message<"prochat.v1.CommunityGroup"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: repeated prochat.v1.Community communities = 3;
   */
  communities: Community[];
};

/**
 * Describes the message prochat.v1.CommunityGroup.
 * Use `create(CommunityGroupSchema)` to create a new message.
 */
export declare const CommunityGroupSchema: GenMessage<CommunityGroup>;

/**
 * @generated from message prochat.v1.Community
 */
export declare type Community = Message<"prochat.v1.Community"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;
};

/**
 * Describes the message prochat.v1.Community.
 * Use `create(CommunitySchema)` to create a new message.
 */
export declare const CommunitySchema: GenMessage<Community>;

