// @generated by protoc-gen-es v2.8.0
// @generated from file prochat/v1/base.proto (package prochat.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file prochat/v1/base.proto.
 */
export const file_prochat_v1_base = /*@__PURE__*/
  fileDesc("ChVwcm9jaGF0L3YxL2Jhc2UucHJvdG8SCnByb2NoYXQudjEiVgoOQ29tbXVuaXR5R3JvdXASCgoCaWQYASABKAkSDAoEbmFtZRgCIAEoCRIqCgtjb21tdW5pdGllcxgDIAMoCzIVLnByb2NoYXQudjEuQ29tbXVuaXR5IiUKCUNvbW11bml0eRIKCgJpZBgBIAEoCRIMCgRuYW1lGAIgASgJQp8BCg5jb20ucHJvY2hhdC52MUIJQmFzZVByb3RvUAFaOWdpdGh1Yi5jb20vdmFyc28vcHJvdGNoYXQtc2VydmVyL2dlbi9wcm9jaGF0L3YxO3Byb2NoYXR2MaICA1BYWKoCClByb2NoYXQuVjHKAgpQcm9jaGF0XFYx4gIWUHJvY2hhdFxWMVxHUEJNZXRhZGF0YeoCC1Byb2NoYXQ6OlYxYgZwcm90bzM");

/**
 * Describes the message prochat.v1.CommunityGroup.
 * Use `create(CommunityGroupSchema)` to create a new message.
 */
export const CommunityGroupSchema = /*@__PURE__*/
  messageDesc(file_prochat_v1_base, 0);

/**
 * Describes the message prochat.v1.Community.
 * Use `create(CommunitySchema)` to create a new message.
 */
export const CommunitySchema = /*@__PURE__*/
  messageDesc(file_prochat_v1_base, 1);

