// @generated by protoc-gen-es v2.8.0
// @generated from file prochat/v1/oauth.proto (package prochat.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file prochat/v1/oauth.proto.
 */
export declare const file_prochat_v1_oauth: GenFile;

/**
 * @generated from message prochat.v1.TokenResponse
 */
export declare type TokenResponse = Message<"prochat.v1.TokenResponse"> & {
  /**
   * @generated from field: string access_token = 1;
   */
  accessToken: string;

  /**
   * @generated from field: string refresh_token = 2;
   */
  refreshToken: string;

  /**
   * @generated from field: int32 access_token_expires_in = 3;
   */
  accessTokenExpiresIn: number;

  /**
   * @generated from field: int32 refresh_token_expires_in = 4;
   */
  refreshTokenExpiresIn: number;

  /**
   * @generated from field: string token_type = 5;
   */
  tokenType: string;

  /**
   * @generated from field: string scope = 6;
   */
  scope: string;
};

/**
 * Describes the message prochat.v1.TokenResponse.
 * Use `create(TokenResponseSchema)` to create a new message.
 */
export declare const TokenResponseSchema: GenMessage<TokenResponse>;

