// @generated by protoc-gen-es v2.8.0
// @generated from file prochat/v1/oauth.proto (package prochat.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file prochat/v1/oauth.proto.
 */
export const file_prochat_v1_oauth = /*@__PURE__*/
  fileDesc("ChZwcm9jaGF0L3YxL29hdXRoLnByb3RvEgpwcm9jaGF0LnYxIqIBCg1Ub2tlblJlc3BvbnNlEhQKDGFjY2Vzc190b2tlbhgBIAEoCRIVCg1yZWZyZXNoX3Rva2VuGAIgASgJEh8KF2FjY2Vzc190b2tlbl9leHBpcmVzX2luGAMgASgFEiAKGHJlZnJlc2hfdG9rZW5fZXhwaXJlc19pbhgEIAEoBRISCgp0b2tlbl90eXBlGAUgASgJEg0KBXNjb3BlGAYgASgJQrABCg5jb20ucHJvY2hhdC52MUIKT2F1dGhQcm90b1ABWklnaXRodWIuY29tL3ZhcnNvL3Byb3RjaGF0LXNlcnZlci9pbnRlcm5hbC9tb2RlbHMvZ2VuL3Byb2NoYXQvdjE7cHJvY2hhdHYxogIDUFhYqgIKUHJvY2hhdC5WMcoCClByb2NoYXRcVjHiAhZQcm9jaGF0XFYxXEdQQk1ldGFkYXRh6gILUHJvY2hhdDo6VjFiBnByb3RvMw");

/**
 * Describes the message prochat.v1.TokenResponse.
 * Use `create(TokenResponseSchema)` to create a new message.
 */
export const TokenResponseSchema = /*@__PURE__*/
  messageDesc(file_prochat_v1_oauth, 0);

